# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ce932b4d01cac8994e3d0540d49c8d54fac3a03c7c14b027d7f1c9dc4c18a7749b89bb08c2aa48ba6acdb7f904e2a2fc377257495b5d103da93de16d8640bf

test:
  secret_key_base: ddca669dbe36875fb93877b63eb205d30747b92ad937e45c6eacb658d454d6c4120a67ffc0c5639125170b33bb4970c2bd5b07f412637f03332fe3bd6e5d4009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
